// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/tictactoe.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpCodes act as the routing mechanism for our WebSocket messages.
// Nakama expects an integer OpCode with every custom message.
type OpCode int32

const (
	OpCode_OPCODE_UNSPECIFIED OpCode = 0
	OpCode_OPCODE_MOVE        OpCode = 1 // Client -> Server: "I want to place my mark"
	OpCode_OPCODE_STATE       OpCode = 2 // Server -> Client: "Here is the updated game state"
	OpCode_OPCODE_GAME_OVER   OpCode = 3 // Server -> Client: "The match has ended"
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "OPCODE_UNSPECIFIED",
		1: "OPCODE_MOVE",
		2: "OPCODE_STATE",
		3: "OPCODE_GAME_OVER",
	}
	OpCode_value = map[string]int32{
		"OPCODE_UNSPECIFIED": 0,
		"OPCODE_MOVE":        1,
		"OPCODE_STATE":       2,
		"OPCODE_GAME_OVER":   3,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_tictactoe_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_api_tictactoe_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_api_tictactoe_proto_rawDescGZIP(), []int{0}
}

// The authoritative Game State broadcasted by the server tick loop
type GameState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A 9-element array representing the 3x3 board.
	// 0 = Empty, 1 = Player X, 2 = Player O
	Board []int32 `protobuf:"varint,1,rep,packed,name=board,proto3" json:"board,omitempty"`
	// Indicates whose turn it is currently (1 or 2)
	CurrentTurn int32 `protobuf:"varint,2,opt,name=current_turn,json=currentTurn,proto3" json:"current_turn,omitempty"`
	// Unix timestamp indicating when the current turn started.
	// Used by the server to enforce the 30-second forfeit rule.
	TurnStartTime int64 `protobuf:"varint,3,opt,name=turn_start_time,json=turnStartTime,proto3" json:"turn_start_time,omitempty"`
	// The Nakama User ID of the winner, or empty if ongoing/draw.
	WinnerId         string `protobuf:"bytes,4,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	P1Id             string `protobuf:"bytes,5,opt,name=p1_id,json=p1Id,proto3" json:"p1_id,omitempty"` // NEW: Player 1 (X)
	P2Id             string `protobuf:"bytes,6,opt,name=p2_id,json=p2Id,proto3" json:"p2_id,omitempty"` // NEW: Player 2 (O)
	IsTimedMode      bool   `protobuf:"varint,7,opt,name=is_timed_mode,json=isTimedMode,proto3" json:"is_timed_mode,omitempty"`
	P1TimeUsed       int64  `protobuf:"varint,8,opt,name=p1_time_used,json=p1TimeUsed,proto3" json:"p1_time_used,omitempty"`
	P2TimeUsed       int64  `protobuf:"varint,9,opt,name=p2_time_used,json=p2TimeUsed,proto3" json:"p2_time_used,omitempty"`
	P1DisconnectTime int64  `protobuf:"varint,10,opt,name=p1_disconnect_time,json=p1DisconnectTime,proto3" json:"p1_disconnect_time,omitempty"` // Unix timestamp when P1 dropped (0 if connected)
	P2DisconnectTime int64  `protobuf:"varint,11,opt,name=p2_disconnect_time,json=p2DisconnectTime,proto3" json:"p2_disconnect_time,omitempty"` // Unix timestamp when P2 dropped (0 if connected)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_api_tictactoe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_api_tictactoe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_api_tictactoe_proto_rawDescGZIP(), []int{0}
}

func (x *GameState) GetBoard() []int32 {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GameState) GetCurrentTurn() int32 {
	if x != nil {
		return x.CurrentTurn
	}
	return 0
}

func (x *GameState) GetTurnStartTime() int64 {
	if x != nil {
		return x.TurnStartTime
	}
	return 0
}

func (x *GameState) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

func (x *GameState) GetP1Id() string {
	if x != nil {
		return x.P1Id
	}
	return ""
}

func (x *GameState) GetP2Id() string {
	if x != nil {
		return x.P2Id
	}
	return ""
}

func (x *GameState) GetIsTimedMode() bool {
	if x != nil {
		return x.IsTimedMode
	}
	return false
}

func (x *GameState) GetP1TimeUsed() int64 {
	if x != nil {
		return x.P1TimeUsed
	}
	return 0
}

func (x *GameState) GetP2TimeUsed() int64 {
	if x != nil {
		return x.P2TimeUsed
	}
	return 0
}

func (x *GameState) GetP1DisconnectTime() int64 {
	if x != nil {
		return x.P1DisconnectTime
	}
	return 0
}

func (x *GameState) GetP2DisconnectTime() int64 {
	if x != nil {
		return x.P2DisconnectTime
	}
	return 0
}

// The payload sent by the client when making a move
type MoveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An integer from 0 to 8 representing the requested grid cell
	Position      int32 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_api_tictactoe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tictactoe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_api_tictactoe_proto_rawDescGZIP(), []int{1}
}

func (x *MoveRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

var File_api_tictactoe_proto protoreflect.FileDescriptor

const file_api_tictactoe_proto_rawDesc = "" +
	"\n" +
	"\x13api/tictactoe.proto\x12\ttictactoe\"\xf7\x02\n" +
	"\tGameState\x12\x14\n" +
	"\x05board\x18\x01 \x03(\x05R\x05board\x12!\n" +
	"\fcurrent_turn\x18\x02 \x01(\x05R\vcurrentTurn\x12&\n" +
	"\x0fturn_start_time\x18\x03 \x01(\x03R\rturnStartTime\x12\x1b\n" +
	"\twinner_id\x18\x04 \x01(\tR\bwinnerId\x12\x13\n" +
	"\x05p1_id\x18\x05 \x01(\tR\x04p1Id\x12\x13\n" +
	"\x05p2_id\x18\x06 \x01(\tR\x04p2Id\x12\"\n" +
	"\ris_timed_mode\x18\a \x01(\bR\visTimedMode\x12 \n" +
	"\fp1_time_used\x18\b \x01(\x03R\n" +
	"p1TimeUsed\x12 \n" +
	"\fp2_time_used\x18\t \x01(\x03R\n" +
	"p2TimeUsed\x12,\n" +
	"\x12p1_disconnect_time\x18\n" +
	" \x01(\x03R\x10p1DisconnectTime\x12,\n" +
	"\x12p2_disconnect_time\x18\v \x01(\x03R\x10p2DisconnectTime\")\n" +
	"\vMoveRequest\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition*Y\n" +
	"\x06OpCode\x12\x16\n" +
	"\x12OPCODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOPCODE_MOVE\x10\x01\x12\x10\n" +
	"\fOPCODE_STATE\x10\x02\x12\x14\n" +
	"\x10OPCODE_GAME_OVER\x10\x03B\x11Z\x0ftic-tac-toe/apib\x06proto3"

var (
	file_api_tictactoe_proto_rawDescOnce sync.Once
	file_api_tictactoe_proto_rawDescData []byte
)

func file_api_tictactoe_proto_rawDescGZIP() []byte {
	file_api_tictactoe_proto_rawDescOnce.Do(func() {
		file_api_tictactoe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tictactoe_proto_rawDesc), len(file_api_tictactoe_proto_rawDesc)))
	})
	return file_api_tictactoe_proto_rawDescData
}

var file_api_tictactoe_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_tictactoe_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_tictactoe_proto_goTypes = []any{
	(OpCode)(0),         // 0: tictactoe.OpCode
	(*GameState)(nil),   // 1: tictactoe.GameState
	(*MoveRequest)(nil), // 2: tictactoe.MoveRequest
}
var file_api_tictactoe_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_tictactoe_proto_init() }
func file_api_tictactoe_proto_init() {
	if File_api_tictactoe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tictactoe_proto_rawDesc), len(file_api_tictactoe_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_tictactoe_proto_goTypes,
		DependencyIndexes: file_api_tictactoe_proto_depIdxs,
		EnumInfos:         file_api_tictactoe_proto_enumTypes,
		MessageInfos:      file_api_tictactoe_proto_msgTypes,
	}.Build()
	File_api_tictactoe_proto = out.File
	file_api_tictactoe_proto_goTypes = nil
	file_api_tictactoe_proto_depIdxs = nil
}
